---
engines:
  eslint:
    enabled: true
    config:
      debug: true
      extensions: [".js", ".jsx"]
  duplication:
    enabled: true
    config:
      languages:
        javascript: {}
  requiresafe:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
  - "Gruntfile.js"
  - "assets/**/*"
