---
engines:
  eslint:
    enabled: true
    config:
      extensions: [".js", ".jsx"]
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          paths:
            - "**/*.js"
            - "**/*.jsx"
  requiresafe:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
