engines:
  eslint:
    enabled: true
    config:
      extensions:
      - .js
      - .jsx
  duplication:
    enabled: true
    config:
      languages:
        javascript: {}
  nodesecurity:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- node_modules/**/*
- config/**/*
- test/**/*
